POST http://localhost:9995/api/v2/ctrls
Content-Type: "application/json"

{
    "name": "ETRI-Controller-5"
}

POST http://localhost:9995/api/v2/svcs
Content-Type: application/json

{
    "msg": "Hello world"
}

PUT http://localhost:9995/api/v2/svcs
id: "51b59a4f-ec0b-49fd-ac6d-e3e7a2c07ec4"