version: '3'

services:
  consul:
    command: agent -ui -bootstrap -server -client 0.0.0.0
    container_name: consul
    hostname: consul
    image: consul:latest
    # networks:
    #   edgex-network: {}
    ports:
      - 9999:8500/tcp
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    user: root:root
    volumes:
      - ./config/consul/:/consul/config:z
    #   - consul-data:/consul/data:z
  centrifugo:
    container_name: centrifugo
    hostname: centrifugo
    image: centrifugo/centrifugo:latest
    restart: always
    ports:
      - 8000:8000/tcp
    volumes:
      - ./config/centrifuge/config.json:/centrifugo/config.json
    command: centrifugo -c config.json
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
  postgres:
    image: postgres:latest
    hostname: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    restart: unless-stopped
    volumes:
      # - ./.data/db/data-14:/var/lib/postgresql/data
      # - ./.data/db/dump:/home
      - /etc/localtime:/etc/localtime:ro
