@serverAddr = dsad
@channel = public:189cb94f-91e0-4617-8fef-f881472b2f6a
POST http://{{serverAddr}}:8000/api
Authorization: apikey aaaf202f-b5f8-4b34-bf88-f6c03a1ecda6
Content-Type: application/json

{
    "method": "publish", 
    "params": {
        "channel": "{{channel}}", 
        "data": {
            "code": 2,
            "ctrlName": "etri-ZXRyaQ==",
            "cmd": "fff"
        }
    }
}